### ISSUE TITLE
Not an Issue: Allow discussion on repo

### ISSUE THREAD

**Issue by mykelbengineer** [CodeDay-Labs-RNZ/Space-saver#23]
You can follow these steps to allow discussions on this repo.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository

Not all are "issues", and discussions can be started to determine if issues should be raised.

**Comment by Seiyaroo** [comment]
Thanks Mykel! We opened it up and discussions should be available now. Great suggestion!
